Sync with 0.20.

diff --git a/init-gofish b/init-gofish
--- a/init-gofish
+++ b/init-gofish
@@ -10,10 +10,20 @@
 pidfile=/var/run/gopherd.pid
 pid=`cat $pidfile 2>/dev/null`
 
+wwwconf=/etc/gofish-www.conf
+wwwpidfile=/var/run/gofish.pid
+wwwpid=`cat $wwwpidfile 2>/dev/null`
+
 if test -n "$pid" && kill -0 $pid 2>/dev/null; then
 	dead=no
 else
 	dead=yes
+fi
+
+if test -n "$wwwpid" && kill -0 $wwwpid 2>/dev/null; then
+	wwwdead=no
+else
+	wwwdead=yes
 fi
 
 die(){
@@ -22,11 +32,23 @@ die(){
 }
 
 case "$1" in
- start)	test "$dead" = yes || die gopherd is already running
-	echo -n "Starting gopherd: "
-	daemon /usr/sbin/gopherd -d
-	touch /var/lock/subsys/gopherd
-	echo_success;echo ''
+ start)	if test "$dead" = no ; then
+	  echo -n "gopherd is already running"; echo_failure; echo ''
+	else
+	  echo -n "Starting gopherd: "
+	  daemon /usr/sbin/gopherd -d
+	  touch /var/lock/subsys/gopherd
+	  echo_success;echo ''
+	fi
+
+	if test -f $wwwconf ; then
+	  test "$wwwdead" = yes || die gofish is already running
+	  echo -n "Starting gofish: "
+	  daemon /usr/sbin/gofish -d -c $wwwconf
+	  touch /var/lock/subsys/gofish
+	  echo_success;echo ''
+	fi
+
 	exit 0
 	;;
   stop)	echo -n "Stopping gopherd: "
@@ -40,7 +62,7 @@ restart) $0 stop; sleep 2; exec $0 start;;
      *)	die "Usage: gopherd {start|stop|restart|status}";;
 esac
 
-test "$dead" = no || die gopherd is not running
+if test "$dead" = no || die gopherd is not running
 kill -$signal $pid
 sleep 2
 kill -0 $pid 2>/dev/null && die "gopherd[$pid] will not die"
